/**
 * 4 kinds: 
 * TaskInvitation	"User 1" invite you to do "Task 1"		Generated By ¿?
 * EventInvitation	"User 1" do "Event 1", you too?'		Generated By ¿?
 * EventPlanning	"User 1" suggest days for do "Event 1"	Generated By ¿?
 * EventStatus		Have you done "Event 1"?				Transforms all past events with "tentative" status to "confirmed" / "cancelled"
 */
define(["DS",'moment','momentlangs'], function(DS,moment,momentlangs){

var Notification = DS.Model.extend({

//Necessary
	kind: DS.attr('string')				//"TaskInvitation", "EventInvitation", "EventPlanning", "EventStatus",
  , created: DS.attr('date')
  , contact: DS.belongsTo('Contact')

//Optional //, { async: true }
  , howMany: DS.belongsTo('HowMany')		//For "TaskInvitation"
  , event: DS.belongsTo('Event')		//For "Event...", have information about their task

//  , isTaskInvitation: function() {
//		return (this.get('kind') === "TaskInvitation");
//	}.property('kind')
  , message: function() {	//summary
		if(this.get('kind') === "TaskInvitation") {
			return '<b>'+this.get('contact').id+'</b> invite you to do HowMany: '+this.get('howMany').id+' Task: '+this.get('howMany').get('task');
		} else if (this.get('kind') === "EventInvitation") {
			return '<b>'+this.get('contact').id+'</b> do '+this.get('event').get('summary')+', you too? id: ('+this.get('event').id+')';
		} else if (this.get('kind') === "EventPlanning") {
			return '<b>'+this.get('contact').id+'</b> suggest days for do '+this.get('event').get('summary')+' id: ('+this.get('event').id+')';
		} else if (this.get('kind') === "EventStatus") {
			return 'Have you done '+this.get('event').get('summary')+'? id: ('+this.get('event').id+')';;
		} else {
			return 'Unknown kind: '+this.get('kind');
		}
	}.property('kind','contact','howMany','event')
  , dateFromNow: function() {
		return moment(this.get('created')).fromNow();
	}.property('created')
});

Notification.FIXTURES = [
	{	id: 1,
		kind: 'TaskInvitation',
//		summary: '"User 1" invite you to do "Task 1"',
		created: '2013-09-17T00:22:02.000Z',
		contact: 'userfixture2@gmail.com',
		howMany: 1
	}
	,{	id: 2,
		kind: 'EventInvitation',
//		summary: '"User 1" do "Event 1", you too?',			
		created: '2013-09-16T00:22:02.000Z',
		contact: 'userfixture2@gmail.com',
		howMany: 1,
		event: '_8d9lcgrfdpr6asjk60oj6c9gcks34phk6gs32cpp6ph62e35c4s3ec9k6oo3aob3c4p0'
	}
	,{	id: 3,
		kind: 'EventPlanning',
//		summary: '"User 1" suggest days for do "Event 1"',
		created: '2013-09-02T00:22:02.000Z',
		contact: 'userfixture2@gmail.com',
		howMany: 1,
		event: '_8d9lcgrfdpr6asjk60rmacpl6sp3aphm6cr38c316kojaopjcdi3ap9jcpj62c1jckqg'
	}
	,{	id: 4,
		kind: 'EventStatus',									//Transforms all past events with "tentative" status to "confirmed" / "cancelled"
//		summary: 'Have you done "Event 1"?',
		created: '2013-08-02T00:22:02.000Z',
		contact: 'userfixture1@gmail.com',
		howMany: 1,
		event: '_8d9lcgrfdpr6asjk60rmacpl6sp3aphm6cr38c316kojaopjcdi3ap9jcpj62c1jckqg'
	}
];

return Notification;
});